# Site setings
name: "judy's devlog"
description: 'Cool Developers never dies'
# Sidebar about text
site_description: ''
logo:
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://forma.netlify.com/
disqus: 'justgoodthemes'
mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: youremail@email.com
contact_page_description: ""
thankyou_page_description: ""

# Social links
twitter: 'username'
facebook: 'username'
github: 'username'
codepen: 'username'
dribbble: 'username'
medium: '@username'
instagram: 'username'
pinterest: 'username'
linkedin: 'username'

# Navigation
navigation:
  - text: About
    url: /about/
  - text: Java
    url: /java/
  - text: Algorithm
    url: /algorithm/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-author-page

# Pagination
paginate: 6
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
