# Site settings
name: "Judy's Devlog"
description: 'Cool developers never die'
site_description: ''
logo:
favicon: 'assets/images/favicon.ico'
baseurl: ""
url: "https://yuju-lee.github.io" # 실제 사이트 URL
disqus: 'devlog-qiqv3mtjda'
mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
ga_analytics: ""

# Contact form settings
email: periq23@gmail.com
contact_page_description: "Forma theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
github: 'yuju-lee'
linkedin: 'yuju-lee'

# Navigation
navigation:
  - text: About me
    url: /about/
  - text: Algorithm
    url: /categories/algorithm/
  - text: Knowledge
    url: /categories/knowledge/
  - text: Logs
    url: /categories/logs/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives

# Pagination
paginate: 6
paginate_path: /page:num/

# Permalinks
permalink: /:categories/:title/

# Archives settings
jekyll-archives:
  enabled:
    - categories
  layouts:
    category: category
  permalinks:
    category: /categories/:name/
    
# Other
markdown: kramdown
highlighter: rouge

# Sass
sass:
  sass_dir: _sass
  style: compressed